# Run Docker Compose with auto-generated secrets on first boot (.env.auto).
# Usage: .\scripts\Compose-Up.ps1 up --build -d
#        .\scripts\Compose-Up.ps1 logs -f api
#
# Optional overrides: create .env in the repo root (see .env.example). Loaded after .env.auto.

$ErrorActionPreference = "Stop"
$Root = Resolve-Path (Join-Path $PSScriptRoot "..")
Set-Location $Root

$autoEnv = if ($env:SUBMIFY_AUTO_ENV) { $env:SUBMIFY_AUTO_ENV } else { Join-Path $Root ".env.auto" }

function New-HexSecret([int] $byteLength) {
    $bytes = New-Object byte[] $byteLength
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $rng.GetBytes($bytes)
    } finally {
        $rng.Dispose()
    }
    return -join ($bytes | ForEach-Object { $_.ToString("x2") })
}

if (-not (Test-Path -LiteralPath $autoEnv)) {
    Write-Host "Creating $autoEnv with auto-generated secrets (first boot)." -ForegroundColor Cyan
    Write-Host "Back up this file with your data - new secrets will not match an existing database." -ForegroundColor DarkYellow
    $pg = New-HexSecret 24
    $jwt = New-HexSecret 32
    $s3 = New-HexSecret 24
    $content = @"
# Auto-generated by scripts/Compose-Up.ps1 - do not commit. Keep with your Postgres / MinIO data.

POSTGRES_PASSWORD=$pg
JWT_SECRET=$jwt
RUSTFS_ROOT_PASSWORD=$s3
"@
    $utf8NoBom = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($autoEnv, $content.TrimEnd() + "`n", $utf8NoBom)
}

$composeArgs = @("compose", "--project-directory", $Root, "--env-file", $autoEnv)
$dotEnv = Join-Path $Root ".env"
if (Test-Path -LiteralPath $dotEnv) {
    $composeArgs += "--env-file"
    $composeArgs += $dotEnv
}

& docker @composeArgs @args
